### ISSUE TITLE
use with grunt-browserify

### ISSUE THREAD

**Issue by andrewc89** [jmm/pathmodify#3]
Is it possible to use the plugin with grunt-browserify? I tried to set it up in a similar fashion to the remapify example in the grunt-browserify README [1] but it doesn't seem to be working.

[1] https://github.com/jmreidy/grunt-browserify#alias

**Comment by jmm** [comment]
Hello @gwely, thanks for your interest! It could be [this issue](https://github.com/jmm/pathmodify/issues/2#issuecomment-125656917) with the way I setup the module's export. It sounds like you could use this [`configure`](https://github.com/jmreidy/grunt-browserify#configure) hook to use `pathmodify` normally with the Browserify API. (I would just do that anyway unless there's a good reason not to.) So I think it'd be something like this:

``` js
var pathmod = require('pathmodify');

options: {
  configure: browserify_configure,
}

function browserify_configure (b) {
  // Note the function call.
  b.plugin(pathmod(), {/* ... */});
}
```

**Comment by andrewc89** [comment]
That worked! Thanks so much.

**Comment by jmm** [comment]
@gwely Great! You're welcome.
