### ISSUE TITLE
couldn't get all tests to pass locally

### ISSUE THREAD

**Issue by dey-dey** [jmm/pathmodify#9]
<img width="503" alt="screen shot 2015-12-19 at 5 06 54 pm" src="https://cloud.githubusercontent.com/assets/796926/11915416/671f9eb6-a673-11e5-9839-cbcfec6a9315.png">

**Comment by jmm** [comment]
@daedelus-j Thanks for the report. Hmm, that's weird -- it seems like something's going wrong with the `sinon.spy()` calls. What is your OS, and versions of Node / npm? Could you try `rm -r node_modules && npm i && npm test`? Currently all tests are passing for me after doing that with Ubuntu 12 and `node@4.21` / `npm@2.14.7` or `node@5.0.0` / `npm@3.3.12`.

**Comment by jmm** [comment]
If this is still a problem please open a new issue with more info. Thanks!
